---
apiVersion: v1
kind: Namespace
metadata:
  name: miner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: miner
  namespace: miner
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: miner
  namespace: miner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: miner
subjects:
- kind: ServiceAccount
  name: default
  namespace: miner
