---
apiVersion: v1
kind: Namespace
metadata:
  name: miner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: miner
  name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: miner
  namespace: miner
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: miner
  namespace: miner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: miner
subjects:
- kind: ServiceAccount
  name: default
  namespace: miner
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: pi
# spec:
#   template:
#     spec:
#       containers:
#       - name: pi
#         env:
#         - name: JOB_NAME
#           value: periodic-ci-openshift-release-master-nightly-4.10-e2e-metal-ipi-ovn-ipv6
#         - name: JOB_ID
#           value: 1451171662442532864
#         - name: JOB_RELEASE:
#           value: 4.10
#         - name: JOB_SIZE:
#           value: 100
#         image: quay.io/jchaloup/ka-audit-miner:3
#         command: ["/bin/bash", "-c"]
#         args:
#           - |
#             . lib.sh
#             export SCRIPT_DIR=/home/app_user
#             processKAAudit /tmp/Data ${JOB_NAME} ${JOB_ID} ${JOB_SIZE}
#             cp /tmp/Data/${JOB_RELEASE}/${JOB_NAME}/${JOB_ID}/ka-audit-logs.json .
#             tar -C /tmp/Data/${JOB_RELEASE}/${JOB_NAME}/${JOB_ID}/ -czf /tmp/file.tar.gz ka-audit-logs.json
#             oc create configmap ${JOB_NAME}-${JOB_ID} --from-file=/tmp/file.tar.gz
#       restartPolicy: Never
#   backoffLimit: 0
